server:
  servlet:
    contextPath: /rest
  port: 8100
  addressurl: https://localhost:3001

spring:
  profiles:
    active: default, test
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dop?serverTimezone=UTC
    username: root
    password: root
  flyway:
    outOfOrder: true
    baselineOnMigrate: true
    placeholderReplacement: false
    locations: classpath:db/initdb, classpath:db/initdata, classpath:db/migration, classpath:db/users
  jackson:
    deserialization:
      fail-on-unknown-properties: false

search:
  server: http://localhost:8983/solr/dop/

app:
  devLogin: true